### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by gmpassos** [vegardit/dart-hotreloader#10]
As informed by pub.dev scores:

```
 The constraint `>=6.0.1 <9.0.0` on vm_service does not support the stable version `9.0.0`, that was published 23 days ago.
When vm_service is 30 days old, this package will no longer be awarded points in this category.
```

To reproduce run:
```
dart pub outdated --no-dev-dependencies --up-to-date --no-dependency-overrides
```

Also I recommend to use the official lints package:

```
dev_dependencies:
  lints: ^2.0.0
```

Regards.

**Comment by sebthom** [comment]
Thanks for the hint. I updated the package.

Regarding the official **lints** package. I don't find it strict enough, so I stick with the **lint** package for now
