### ISSUE TITLE
Option to accept alternate project paths

### ISSUE THREAD

**Issue by pattobrien** [vegardit/dart-hotreloader#11]
First and foremost, thank you for such a great, useful package!

I'm using `hotreloader` in my custom lint rule package [sidecar](https://github.com/pattobrien/sidecar) (currently in alpha testing). For context, the package generates an analyzer bootloader file in `.dart_tool` directory of the target package, which is then run by the dart analysis server in order to generate lints for the target. In other words, there are two different projects within the same directory (e.g. `counter_app` and `counter_app/.dart_tool/counter_app_lints`).

I would like the ability to send alternate project paths to hot reloader (in the above case, it would be the package path of `counter_app_lints`) so that the server can be restarted when the lint files are changed. I'm very willing to help support this use case with a PR, but want to gather thoughts here first.

**Comment by sebthom** [comment]
Dear Patt, thanks for your kind words! A respective PR would be most welcomed.

**Comment by pattobrien** [comment]
Great! will get on it soon :)
