### ISSUE TITLE
Does not track dependency overrides ?

### ISSUE THREAD

**Issue by pisabev** [vegardit/dart-hotreloader#3]
I'm using something like this in development:

dependencies:
  sompackage:
    git: git@url_to_the_package

dependency_overrides:
  sompackage:
    path: /local/path/to/the/package

It seems that this configuration is not supported.

**Comment by sebthom** [comment]
This should work with dependency_overrides too. 

What does your `.dart_tool/package_config.json` contain regarding the package?

Did you try running `dart pub get` after you added the override?

**Comment by pisabev** [comment]
Here is a snippet of package_config.json:

    {
      "name": "hms_connect",
      "rootUri": "../../hms_connect",
      "packageUri": "lib/",
      "languageVersion": "2.10"
    },
    {
      "name": "hms_contractor",
      "rootUri": "../../hms_contractor",
      "packageUri": "lib/",
      "languageVersion": "2.10"
    },
    {
      "name": "hms_define",
      "rootUri": "../../hms_define",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },

I'm successfully using hotreloader in another package which uses relative paths too, but no depdendencies_overrides.
