### ISSUE TITLE
Not compatbile with integration_test

### ISSUE THREAD

**Issue by shinayser** [vegardit/dart-hotreloader#4]
Hello folks!

We have an app that uses the flutter's official package `integration_test` that currently uses `vm_service: 7.1.1` as a dependency.
Unfortunately, `hotreloader` is using only version `6.0.1` of the same package, thus making those two libs uncompatible. 

Do you folks intend to update the `vm_service` to make it compatible with `integration_test` ?

Here goes a picture of the problem:

![image](https://user-images.githubusercontent.com/1146982/148073405-8b0a813a-dc06-465f-917b-71687f2f4e64.png)
_Yes, I know that we would still need an update for `shelf_hotreload` but I can arrange that in a second step :)_

**Comment by BlackLeg15** [comment]
Up

**Comment by sebthom** [comment]
Thanks for reporting!

**Comment by shinayser** [comment]
Thank you very much for your work @sebthom ! Any plans on publishing this version on pub.dev?

**Comment by sebthom** [comment]
@shinayser I am going to address some of the new linter rules and then hopefully release it today.

**Comment by sebthom** [comment]
@shinayser I just released 3.0.2. please give it a try.
