### ISSUE TITLE
Awaiting HotReloader.stop() causes program to wait forever

### ISSUE THREAD

**Issue by Keithcat1** [vegardit/dart-hotreloader#6]
Windows 10 (64-bit)
Dart SDK version: 2.16.1 (stable) (Tue Feb 8 12:02:33 2022 +0100) on "windows_x64"                                                                                      

The simplest example code that reproduces the problem is:
```dart
import "package:hotreloader/hotreloader.dart";
void main() async {
	final hotreloader = await HotReloader.create();
	print("Stopping hotreloader");
	await hotreloader.stop();
}
```
The command line output when using "dart run --enable-vm-service":
Observatory listening on http://127.0.0.1:8181/gXzhbqj9NNE=/
The Dart DevTools debugger and profiler is available at: http://127.0.0.1:8181/gXzhbqj9NNE=/devtools/#/?uri=ws%3A%2F%2F127.0.0.1%3A8181%2FgXzhbqj9NNE%3D%2Fws
Stopping hotreloader
...
...

**Comment by sebthom** [comment]
Thanks for reporting! I released version 3.0.3 which should fix this issue.
