### ISSUE TITLE
FileSystemException: Exists failed, path = '/usr/lib/dart/bin/resources/devtools'

### ISSUE THREAD

**Issue by weenzeel** [vegardit/dart-hotreloader#8]
I'm trying to run a program that will perform a build-script when source files changes.
Getting the error message below.

Running in a Github Codespace (created from the docker template for Dart in the following repository: https://github.com/microsoft/vscode-dev-containers/tree/main/containers/dart).

Does the library expect some system level dependencies? (Dev tools?)

I'm running on Dart 2.16.2. Using nothing but the code in the sample code given for this library in the Readme file.

Thanks!

Could not start Observatory HTTP server:
FileSystemException: Exists failed, path = '/usr/lib/dart/bin/resources/devtools' (OS Error: Permission denied, errno = 13)
#0      _Directory.existsSync (dart:io/directory_impl.dart:94:7)
#1      createStaticHandler (package:shelf_static/src/static_handler.dart:49:16)
#2      devtoolsHandler (package:dds/src/devtools/devtools_handler.dart:29:32)
#3      DartDevelopmentServiceImpl._httpHandler (package:dds/src/dds_impl.dart:300:14)
#4      DartDevelopmentServiceImpl._handlers (package:dds/src/dds_impl.dart:262:14)
#5      DartDevelopmentServiceImpl._startDDSServer (package:dds/src/dds_impl.dart:151:41)
#6      DartDevelopmentServiceImpl.startService (package:dds/src/dds_impl.dart:113:13)
<asynchronous suspension>
#7      DartDevelopmentService.startDartDevelopmentService (package:dds/dds.dart:88:5)
<asynchronous suspension>
#8      main (file:///b/s/w/ir/cache/builder/sdk/pkg/dds/bin/dds.dart:52:17)
<asynchronous suspension>

**Comment by sebthom** [comment]
The library relies on Dart's [internal hot reload](https://github.com/dart-lang/sdk/wiki/Hot-reload) capability which is exposed via the [vm_service](https://pub.dev/packages/vm_service) package. This depends on the  DartDevelopmentService which is part of the devtools (which is included in the DartSDK) and probably missing from the container image you are using. See also https://groups.google.com/a/dartlang.org/g/reviews/c/5s1m0XBAgws

**Comment by weenzeel** [comment]
The devtools are there, but there seems to be a problem with permissions to certain paths on linux in the SDK.

https://github.com/dart-lang/dart-docker/issues/62
https://github.com/dart-lang/sdk/issues/47093

In the Docker file that my dev-container is built on ... there is a workaround in the docker file ... adding permissions to certain folders explicitly.

... && chmod 755 "$DART_SDK" "$DART_SDK/bin"

If I add "$DART_SDK/bin/resources" to the list of folders (and rebuilds the container) the error message above goes away.
