### ISSUE TITLE
Package directories are not watched correctly

### ISSUE THREAD

**Issue by schultek** [vegardit/dart-hotreloader#9]
I have two local packages, that have paths like this:

- some/path/package/some_package
- some/path/package/some_package_b

Since the first package path is a complete prefix of the second package path, the below code causes the issue that the second package is not watched altogether:

https://github.com/vegardit/dart-hotreloader/blob/29f21468dd0188c94c9325a12c8c51ff6b78594d/lib/hotreloader.dart#L185-L188

**Comment by sebthom** [comment]
Thanks for reporting! Please try the new version 3.0.4.
